language: python
python:
    - "3.7"

services:
    - docker
    
before_install: 
    - docker build -t graphql-flask:latest .
    - docker run -d -p 5000:5000 graphql-flask /bin/sh -c "coverage run -m pytest"
    - docker ps -a